# Generated by Django 3.2.16 on 2023-01-13 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230113_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='business',
        ),
        migrations.AlterField(
            model_name='business',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 17, 23, 37, 549376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 17, 23, 37, 553314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 17, 23, 37, 552722, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 17, 23, 37, 546043, tzinfo=utc)),
        ),
    ]
