# Generated by Django 3.2.16 on 2023-01-13 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230113_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 17, 59, 51, 605726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 17, 59, 51, 610482, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 17, 59, 51, 609512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 17, 59, 51, 602413, tzinfo=utc)),
        ),
    ]
