# Generated by Django 3.2.16 on 2023-01-13 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230113_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 19, 11, 15, 562491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 19, 11, 15, 567393, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 19, 11, 15, 566724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 19, 11, 15, 557575, tzinfo=utc)),
        ),
    ]
